apiVersion: v1
data:
  POSTGRES_DB: hello_flask_dev
  POSTGRES_PASSWORD: hello_flask
  POSTGRES_USER: hello_flask
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db-database-database-env
  name: database-database-env
